Add ::names ::values ::toArray helper to BackedEnum
PrinsFrank/standards pull request #33
Opened 2022-07-24 03:21 UTC by lakuapik

This PR add static function `names()`, `values()` and `toArray` in the BackendEnum class.

```php
use PrinsFrank\Standards\BackedEnum;
use PrinsFrank\Standards\Language\ISO639_1_Alpha_2;

$array = BackedEnum::toArray(ISO639_1_Alpha_2::class);
$values = BackedEnum::values(ISO639_1_Alpha_2::class);
$names = BackedEnum::names(ISO639_1_Alpha_2::class);
```

This maybe useful and maybe not. Feel free to accept or drop this PR. Cheers :clinking_glasses: 

---

Apart from this, @PrinsFrank  what do you think instead of using it with BackedEnum class, 
use directly in the enum class it self. Like:

```php
use PrinsFrank\Standards\Language\ISO639_1_Alpha_2;

$array = ISO639_1_Alpha_2::toArray();
$values = ISO639_1_Alpha_2::values();
$names = ISO639_1_Alpha_2::names();

// and maybe add toJson too
$json = ISO639_1_Alpha_2::toJson();
```

2022-08-14 16:27 UTC, PrinsFrank commented
@lakuapik Thanks for your contribution! As enums cannot extend othere classes and adding traits to implement generic logic across enums is not preferrable, I think your current solution is the best one. 

Until now, the BackenEnum class in this package was mainly for internal use, so adding these methods that are not used internally means that any breaking changes to them mean a major semver release. I do think they add value for package users, so I will merge this when this branch is passing.

2022-08-14 16:31 UTC, PrinsFrank requested changes
I don't know if you intentionaly didn't fix the phpstan issues or if you were struggling what the return type array shape should be, so I've added three recomendations that should fix the pipeline.

2022-08-14 16:31 UTC, PrinsFrank commented on src/BackedEnum.php
> +     * @return array
```suggestion
     * @return array<positive-int, key-of<T>>
```

2022-08-14 16:31 UTC, PrinsFrank commented on src/BackedEnum.php
> +     * @return array
```suggestion
     * @return array<positive-int, value-of<T>>
```

2022-08-14 16:31 UTC, PrinsFrank commented on src/BackedEnum.php
> +     * @return array
```suggestion
     * @return array<key-of<T>, value-of<T>>
```

2022-08-18 14:25 UTC, lakuapik commented
@PrinsFrank i've ajusted the codestyle.

---

Anyway, why adding trait to Enum is not preferable to you, im curious, may i know your reason?

2022-08-18 18:01 UTC, PrinsFrank commented
@lakuapik I don't know why, but you pipelines were not starting. I've started them manually and fixed the issues. Apparently, even though the PHPStan documentation says that value-of<> for Backed enums is supported, it isn't. Or at least not in combination with generics. 

Now as for your question why adding traits to enums is not preferrable: There are a bunch of issues with traits in PHP, so I try to avoid them in general. I think I've only found 1 valid use case for traits in the past 4 years. An excellent write up can be found here: https://codereview.stackexchange.com/questions/74077/trait-accessing-variables-of-classes-using-it

2022-08-18 18:29 UTC, PrinsFrank approved these changes
I didn't notice this in my review, but it was not enforced before that the parameter FQN should actually be for an enum class. I've fixed that, and it looks good now! Thanks for your contribution!

2022-08-18 18:29 UTC, merged